siteTitle = "Autoplovyklos"
siteDescr = "Technologijų antreprenerystė"
siteAuthor = "Autoplovyklos"

siteFacebookUrl = "https://www.facebook.com/KTUTechnologyEntrepreneurshipProgramme/?fref=ts"
siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/ktunews"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/blog-tep"